# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/predictor.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2
from api import prompter_pb2 as api_dot_prompter__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pi/predictor.proto\x12\x03\x61pi\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x12\x61pi/prompter.proto\"!\n\x0ePrepareDataReq\x12\x0f\n\x07sources\x18\x01 \x03(\t\"K\n\nPredictReq\x12\x1c\n\x04type\x18\x01 \x01(\x0e\x32\x0e.api.QueryType\x12\x0f\n\x07product\x18\x02 \x01(\t\x12\x0e\n\x06period\x18\x03 \x01(\t\"\x1b\n\x0bPredictResp\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"1\n\x0fUniqueCodesResp\x12\x1e\n\x05\x63odes\x18\x01 \x03(\x0b\x32\x0f.api.UniqueCode\"<\n\nUniqueCode\x12\x0f\n\x07segment\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07regular\x18\x03 \x01(\x08\x32\xb8\x01\n\tPredictor\x12<\n\x0bPrepareData\x12\x13.api.PrepareDataReq\x1a\x16.google.protobuf.Empty\"\x00\x12.\n\x07Predict\x12\x0f.api.PredictReq\x1a\x10.api.PredictResp\"\x00\x12=\n\x0bUniqueCodes\x12\x16.google.protobuf.Empty\x1a\x14.api.UniqueCodesResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.predictor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREPAREDATAREQ']._serialized_start=188
  _globals['_PREPAREDATAREQ']._serialized_end=221
  _globals['_PREDICTREQ']._serialized_start=223
  _globals['_PREDICTREQ']._serialized_end=298
  _globals['_PREDICTRESP']._serialized_start=300
  _globals['_PREDICTRESP']._serialized_end=327
  _globals['_UNIQUECODESRESP']._serialized_start=329
  _globals['_UNIQUECODESRESP']._serialized_end=378
  _globals['_UNIQUECODE']._serialized_start=380
  _globals['_UNIQUECODE']._serialized_end=440
  _globals['_PREDICTOR']._serialized_start=443
  _globals['_PREDICTOR']._serialized_end=627
# @@protoc_insertion_point(module_scope)
