basePath: /
definitions:
  model.ListResp:
    properties:
      sessions:
        items:
          $ref: '#/definitions/model.SessionDto'
        type: array
    type: object
  model.LoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.LoginResp:
    properties:
      token:
        type: string
    type: object
  model.NewSessionResp:
    properties:
      id:
        type: string
    type: object
  model.RenameReq:
    properties:
      id:
        type: string
      title:
        maxLength: 25
        minLength: 3
        type: string
    required:
    - id
    - title
    type: object
  model.SessionDto:
    properties:
      created_at:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
host: localhost:10000
info:
  contact: {}
  description: Документация API чат-сервиса команды misis.tech
  license:
    name: BSD-3-Clause
    url: https://opensource.org/license/bsd-3-clause
  title: Chat service API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Авторизоваться в системе, используя логин и пароль
      parameters:
      - description: Запрос на авторизацию
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: Успешная авторизация
          schema:
            $ref: '#/definitions/model.LoginResp'
        "400":
          description: Неверный запрос
          schema:
            type: string
        "401":
          description: Неверный данные для входа
          schema:
            type: string
        "422":
          description: Ошибка валидации данных
          schema:
            type: string
      summary: Авторизация
      tags:
      - auth
  /session/{id}:
    delete:
      consumes:
      - application/json
      description: Удалить сессию по ID
      parameters:
      - description: access token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Сессия удалена
          schema:
            type: string
        "400":
          description: Неверное значение ID
          schema:
            type: string
        "404":
          description: Сессия с таким ID не найдена
          schema:
            type: string
      summary: Удалить сессию
      tags:
      - session
  /session/list:
    get:
      consumes:
      - application/json
      description: Получить список сессий в порядке убывания момента создания от последней
        к первой для авторизованного пользователя
      parameters:
      - description: access token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список сессий
          schema:
            $ref: '#/definitions/model.ListResp'
      summary: Список сессий
      tags:
      - session
  /session/new:
    post:
      consumes:
      - application/json
      description: Создать новую сессию в чате для авторизованного пользователя
      parameters:
      - description: access token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: ID новой сессии
          schema:
            $ref: '#/definitions/model.NewSessionResp'
        "400":
          description: Сессия с таким ID уже существует
          schema:
            type: string
      summary: Новая сессия
      tags:
      - session
  /session/rename:
    put:
      consumes:
      - application/json
      description: Обновить заголовок сессии, который отображается в интерфейсе
      parameters:
      - description: access token
        in: header
        name: token
        required: true
        type: string
      - description: ID и новое название сессии
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.RenameReq'
      produces:
      - application/json
      responses:
        "204":
          description: Сессия переименована
          schema:
            type: string
        "400":
          description: Сессия с таким ID уже существует
          schema:
            type: string
        "404":
          description: Сессия с таким ID не найдена
          schema:
            type: string
      summary: Обновить заголовок
      tags:
      - session
swagger: "2.0"
