server:
  port: 12000
  log_level: "debug"
  cors_origins:
    - "https://your-domain.com"
  cipher_key: "32bit hex value"

keycloak:
  url: "http://192.168.1.80:8080"
  client_secret: "client secret"
  realm: "ldt"
  admin_realm: "master"
  user: "kcuser"
  password: "kcpass"

postgres:
  user: "pguser"
  password: "pgpass"
  host: "192.168.1.80"
  port: 5432
  db: "dev"
  ssl: false
  retry_timeout: 20

jaeger:
  host: "192.168.1.80"
  port: 4318

s3:
  host: "192.168.1.80"
  port: 9000
  access_key: "access_key"
  secret_key: "secret_key"
  ssl: false

prom:
  host: ""
  port: 12001

api:
  host: "192.168.1.80"
  port: 9999