# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from api import prompter_pb2 as api_dot_prompter__pb2


class PrompterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Extract = channel.unary_unary(
                '/api.Prompter/Extract',
                request_serializer=api_dot_prompter__pb2.ExtractReq.SerializeToString,
                response_deserializer=api_dot_prompter__pb2.ExtractedPrompt.FromString,
                )


class PrompterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Extract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrompterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Extract': grpc.unary_unary_rpc_method_handler(
                    servicer.Extract,
                    request_deserializer=api_dot_prompter__pb2.ExtractReq.FromString,
                    response_serializer=api_dot_prompter__pb2.ExtractedPrompt.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.Prompter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Prompter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Extract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.Prompter/Extract',
            api_dot_prompter__pb2.ExtractReq.SerializeToString,
            api_dot_prompter__pb2.ExtractedPrompt.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
