# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/prompter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61pi/prompter.proto\x12\x03\x61pi\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xca\x01\n\nExtractReq\x12\x0e\n\x06prompt\x18\x01 \x01(\t:\xab\x01\x92\x41\xa7\x01\nI*\x16\x45xtract prompt request2&Extracts required metadata from prompt\xd2\x01\x06prompt2Z{\"prompt\": \"\xd1\x8f \xd1\x85\xd0\xbe\xd1\x87\xd1\x83 \xd0\xba\xd1\x83\xd0\xbf\xd0\xb8\xd1\x82\xd1\x8c \xd0\xb1\xd1\x83\xd0\xbc\xd0\xb0\xd0\xb3\xd1\x83 A4 \xd0\xbd\xd0\xb0 18 \xd0\xbc\xd0\xb5\xd1\x81\xd1\x8f\xd1\x86\xd0\xb5\xd0\xb2 \xd0\xb2\xd0\xbf\xd0\xb5\xd1\x80\xd0\xb5\xd0\xb4\"}\"\xd4\x01\n\x0f\x45xtractedPrompt\x12\x1c\n\x04type\x18\x01 \x01(\x0e\x32\x0e.api.QueryType\x12\x0f\n\x07product\x18\x02 \x01(\t:\x91\x01\x92\x41\x8d\x01\n`*\x17\x45xtract prompt response24Metadata from raw prompt that is passed to predictor\xd2\x01\x04type\xd2\x01\x07product2){\"type\": 1, \"product\": \"\xd0\xb1\xd1\x83\xd0\xbc\xd0\xb0\xd0\xb3\xd0\xb0 A4\"}*5\n\tQueryType\x12\r\n\tUNDEFINED\x10\x00\x12\x0e\n\nPREDICTION\x10\x01\x12\t\n\x05STOCK\x10\x02\x32\x61\n\x08Prompter\x12U\n\x07\x45xtract\x12\x0f.api.ExtractReq\x1a\x14.api.ExtractedPrompt\"#\x82\xd3\xe4\x93\x02\x1d\"\x18/api/v1/prompter/extract:\x01*B\x11Z\x0finternal/api/pbb\x06proto3')

_QUERYTYPE = DESCRIPTOR.enum_types_by_name['QueryType']
QueryType = enum_type_wrapper.EnumTypeWrapper(_QUERYTYPE)
UNDEFINED = 0
PREDICTION = 1
STOCK = 2


_EXTRACTREQ = DESCRIPTOR.message_types_by_name['ExtractReq']
_EXTRACTEDPROMPT = DESCRIPTOR.message_types_by_name['ExtractedPrompt']
ExtractReq = _reflection.GeneratedProtocolMessageType('ExtractReq', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTREQ,
  '__module__' : 'api.prompter_pb2'
  # @@protoc_insertion_point(class_scope:api.ExtractReq)
  })
_sym_db.RegisterMessage(ExtractReq)

ExtractedPrompt = _reflection.GeneratedProtocolMessageType('ExtractedPrompt', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTEDPROMPT,
  '__module__' : 'api.prompter_pb2'
  # @@protoc_insertion_point(class_scope:api.ExtractedPrompt)
  })
_sym_db.RegisterMessage(ExtractedPrompt)

_PROMPTER = DESCRIPTOR.services_by_name['Prompter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017internal/api/pb'
  _EXTRACTREQ._options = None
  _EXTRACTREQ._serialized_options = b'\222A\247\001\nI*\026Extract prompt request2&Extracts required metadata from prompt\322\001\006prompt2Z{\"prompt\": \"\321\217 \321\205\320\276\321\207\321\203 \320\272\321\203\320\277\320\270\321\202\321\214 \320\261\321\203\320\274\320\260\320\263\321\203 A4 \320\275\320\260 18 \320\274\320\265\321\201\321\217\321\206\320\265\320\262 \320\262\320\277\320\265\321\200\320\265\320\264\"}'
  _EXTRACTEDPROMPT._options = None
  _EXTRACTEDPROMPT._serialized_options = b'\222A\215\001\n`*\027Extract prompt response24Metadata from raw prompt that is passed to predictor\322\001\004type\322\001\007product2){\"type\": 1, \"product\": \"\320\261\321\203\320\274\320\260\320\263\320\260 A4\"}'
  _PROMPTER.methods_by_name['Extract']._options = None
  _PROMPTER.methods_by_name['Extract']._serialized_options = b'\202\323\344\223\002\035\"\030/api/v1/prompter/extract:\001*'
  _QUERYTYPE._serialized_start=525
  _QUERYTYPE._serialized_end=578
  _EXTRACTREQ._serialized_start=106
  _EXTRACTREQ._serialized_end=308
  _EXTRACTEDPROMPT._serialized_start=311
  _EXTRACTEDPROMPT._serialized_end=523
  _PROMPTER._serialized_start=580
  _PROMPTER._serialized_end=677
# @@protoc_insertion_point(module_scope)
