server:
  chat_port: 10000
  bot_port: 11000
  log_level: "debug"
  cors_origins:
    - "*"
  cipher_key: "32-bit cipher hex key"
  bot_token: "BOT:TOKEN"
  debug_mode: true

keycloak:
  url: "http://keycloak:8080"
  realm: "ldt"

postgres:
  user: "pguser"
  password: "pgpass"
  host: "pg"
  port: 5432
  db: "dev"
  ssl: false
  retry_timeout: 20

redis:
  username: ""
  password: "redispass"
  host: "localhost"
  port: 6379
  db: 0

jaeger:
  host: "jaeger"
  port: 4318

chat_prom:
  host: ""
  port: 10001

bot_prom:
  host: ""
  port: 11001

api:
  host: "api"
  port: 9999
