server:
  port: 10000
  log_level: "debug"
  cors_origins:
    - "https://your-domain.com"
  cipher_key: "32bit hex string"
  bot_token: "BOT:TOKEN"
  app_url: "https://you-domain.com"

keycloak:
  url: "http://192.168.1.80:8080"
  realm: "ldt"

postgres:
  user: "pguser"
  password: "pgpass"
  host: "192.168.1.80"
  port: 5432
  db: "dev"
  ssl: false
  retry_timeout: 20

jaeger:
  host: "192.168.1.80"
  port: 4318

prom:
  host: ""
  port: 10001

api:
  host: "192.168.1.80"
  port: 9999