// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: api/predictor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Predictor_PrepareData_FullMethodName = "/api.Predictor/PrepareData"
	Predictor_Predict_FullMethodName     = "/api.Predictor/Predict"
	Predictor_UniqueCodes_FullMethodName = "/api.Predictor/UniqueCodes"
)

// PredictorClient is the client API for Predictor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PredictorClient interface {
	PrepareData(ctx context.Context, in *PrepareDataReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Predict(ctx context.Context, in *PredictReq, opts ...grpc.CallOption) (*PredictResp, error)
	UniqueCodes(ctx context.Context, in *UniqueCodesReq, opts ...grpc.CallOption) (*UniqueCodesResp, error)
}

type predictorClient struct {
	cc grpc.ClientConnInterface
}

func NewPredictorClient(cc grpc.ClientConnInterface) PredictorClient {
	return &predictorClient{cc}
}

func (c *predictorClient) PrepareData(ctx context.Context, in *PrepareDataReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Predictor_PrepareData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *predictorClient) Predict(ctx context.Context, in *PredictReq, opts ...grpc.CallOption) (*PredictResp, error) {
	out := new(PredictResp)
	err := c.cc.Invoke(ctx, Predictor_Predict_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *predictorClient) UniqueCodes(ctx context.Context, in *UniqueCodesReq, opts ...grpc.CallOption) (*UniqueCodesResp, error) {
	out := new(UniqueCodesResp)
	err := c.cc.Invoke(ctx, Predictor_UniqueCodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PredictorServer is the server API for Predictor service.
// All implementations must embed UnimplementedPredictorServer
// for forward compatibility
type PredictorServer interface {
	PrepareData(context.Context, *PrepareDataReq) (*emptypb.Empty, error)
	Predict(context.Context, *PredictReq) (*PredictResp, error)
	UniqueCodes(context.Context, *UniqueCodesReq) (*UniqueCodesResp, error)
	mustEmbedUnimplementedPredictorServer()
}

// UnimplementedPredictorServer must be embedded to have forward compatible implementations.
type UnimplementedPredictorServer struct {
}

func (UnimplementedPredictorServer) PrepareData(context.Context, *PrepareDataReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareData not implemented")
}
func (UnimplementedPredictorServer) Predict(context.Context, *PredictReq) (*PredictResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedPredictorServer) UniqueCodes(context.Context, *UniqueCodesReq) (*UniqueCodesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UniqueCodes not implemented")
}
func (UnimplementedPredictorServer) mustEmbedUnimplementedPredictorServer() {}

// UnsafePredictorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PredictorServer will
// result in compilation errors.
type UnsafePredictorServer interface {
	mustEmbedUnimplementedPredictorServer()
}

func RegisterPredictorServer(s grpc.ServiceRegistrar, srv PredictorServer) {
	s.RegisterService(&Predictor_ServiceDesc, srv)
}

func _Predictor_PrepareData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictorServer).PrepareData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Predictor_PrepareData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictorServer).PrepareData(ctx, req.(*PrepareDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Predictor_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictorServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Predictor_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictorServer).Predict(ctx, req.(*PredictReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Predictor_UniqueCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UniqueCodesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictorServer).UniqueCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Predictor_UniqueCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictorServer).UniqueCodes(ctx, req.(*UniqueCodesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Predictor_ServiceDesc is the grpc.ServiceDesc for Predictor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Predictor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Predictor",
	HandlerType: (*PredictorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareData",
			Handler:    _Predictor_PrepareData_Handler,
		},
		{
			MethodName: "Predict",
			Handler:    _Predictor_Predict_Handler,
		},
		{
			MethodName: "UniqueCodes",
			Handler:    _Predictor_UniqueCodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/predictor.proto",
}
