server:
  port: 9999
  log_level: "debug"
  gateway_port: 9998

keycloak:
  url: "http://192.168.1.80:8080"
  client_id: "ldt-client"
  client_secret: "client secret"
  realm: "ldt"
  admin_realm: "master"
  user: "kcuser"
  password: "kcpass"

postgres:
  user: "pguser"
  password: "pgpass"
  host: "192.168.1.80"
  port: 5432
  db: "dev"
  ssl: false
  retry_timeout: 20

jaeger:
  host: "192.168.1.80"
  port: 4318

prometheus:
  host: ""
  port: 9991

prompter:
  host: "192.168.1.80"
  port: 9990

predictor:
  host: "192.168.1.80"
  port: 9980

mongo:
  host: "192.168.1.80"
  port: 27017
  db: "product"
  auth_type: "no"
  retry_timeout: 20